### ISSUE TITLE
You can do this with the Windows API

### ISSUE THREAD

**Issue by HypsyNZ** [ZeroMemoryEx/Tokenizer#2]
You don't need a Kernel Mode driver to do this.. You can do it with the Windows API and ROP.

https://github.com/HypsyNZ/Trusted-Launcher

Nice project, Just saying for people who don't want to use a KMD for something so simple.

Thanks for pointing out how flawed all of this is.

**Comment by ZeroMemoryEx** [comment]
Hello @HypsyNZ, yes, I know that you can impersonate other processes' tokens from user mode, but I chose to create a kernel mode driver because it provides me with full control over the system. With a kernel mode driver, I can even manipulate protected processes, which cannot be done from user mode ...
